Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,94 +1,117 @@
-name: Build
+name: Build and Release YTMusicUltimate
 on:
   workflow_dispatch:
-    inputs:
-      sdk_version:
-        description: "iOS SDK Version"
-        type: choice
-        options:
-          - 16.5
-          - 17.5
-          - 18.6
-        required: true
-        default: 16.5
-
-      url:
+    inputs: 
+      ipa_url:
         description: "URL to the decrypted IPA file"
         default: ""
+        required: true
+        type: string
+
+      display_name:
+        description: "App Name (Optional)"
+        default: "YouTube Music"
+        required: true
+        type: string
+
+      bundle_id:
+        description: "BundleID (Optional)"
+        default: "com.google.ios.youtubemusic"
         required: true
         type: string
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
-  
+
 jobs:
   build:
-    name: Build
+    name: Build YTMusicUltimate
     runs-on: macos-latest
     permissions:
       contents: write
-    ## Force Node.js 24 (Temporary fix for the Github Releases Node.js 20 warnings)
-    # env:
-    #   ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
 
     steps:
-      - name: Clone
+      - name: Checkout Main
+        uses: actions/checkout@v6.0.2
+        with:
+          path: main
+          submodules: recursive
+
+      - name: Hide sensitive inputs
+        uses: levibostian/action-hide-sensitive-inputs@v1
+        with:
+          exclude_inputs: bundle_id,display_name
+
+      - name: Validate IPA URL
         run: |
-          git clone --quiet https://github.com/Tonwalter888/YTMusicUltimatePlus.git
-          wget "${{ inputs.url }}" -O youtube.ipa
+          curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
+          file_type=$(file --mime-type -b sample.part)
+
+          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
+            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
+            exit 1
+          fi
 
       - name: Install Dependencies
         run: brew install make ldid
 
-      - name: Set PATH environments variable
+      - name: Set PATH environment variables
         run: |
           echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
-          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV 
+          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
+
+      - name: Cache Theos
+        id: theos
+        uses: actions/cache@v5.0.3
+        env:
+          cache-name: theos_cache_344ee59
+        with:
+          path: theos/
+          key: ${{ env.cache-name }}
+          restore-keys: ${{ env.cache-name }}
 
       - name: Setup Theos
-        run: git clone --quiet --recurse-submodules https://github.com/theos/theos.git
+        if: steps.theos.outputs.cache-hit != 'true'
+        uses: actions/checkout@v6.0.2
+        with:
+          repository: theos/theos
+          ref: 344ee5925df036dbd1312b783ad5a00d153c2445
+          path: theos
+          submodules: recursive
 
       - name: Download iOS SDK
+        if: steps.theos.outputs.cache-hit != 'true'
         run: |
           git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git
           cd sdks
-          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
+          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
           git checkout
           mv *.sdk $THEOS/sdks
 
       - name: Install cyan
         run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
 
-      - name: Clone YouTubeHeader
-        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git $THEOS/include/YouTubeHeader
-          
-      #- name: Clone PSHeader
-      #  run: git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git $THEOS/include/PSHeader
+      - name: Download YouTube Music
+        id: download_youtube_music
+        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ytm.ipa
 
-      - name: Build
+      - name: Build Tweak for Sideloading
         run: |
-          cd YTMusicUltimatePlus
-          git switch updatetweak
-          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless SIDELOADING=1
-          mv packages/*.deb ${{ github.workspace }}/ytmult.deb
+          cd main
+          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless SIDELOADING=1
+          mv packages/*.deb ../ytmult.deb
 
-      - name: Inject Tweaks Into IPA
-        run: |
-          tweaks=""
-          
-          for f in *.deb; do
-            if [ -f "$f" ]; then
-              tweaks="$tweaks $f"
-            fi
-          done
-          
-          cyan -i youtube.ipa -o WaterTest.ipa -uwef $tweaks -n "WaterTest" -b com.waterdev.youtube
-          
-      - name: Create a Draft Release
+      - name: Inject tweak into provided IPA
+        run: cyan -i ytm.ipa -o YTMusicUltimate.ipa -uwsf ytmult.deb -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }} 
+
+      - name: Create Release
         uses: softprops/action-gh-release@v2.5.0
         with:
-          tag_name: watertest-ipa${{ github.run_number }}
-          name: WaterTest (${{ github.run_number }}) 
-          files: WaterTest.ipa
+          name: YTMusicUltimate-v${{ github.run_number }}
+          files: YTMusicUltimate.ipa
           draft: true
+
+      - name: Output Release URL
+        run: |
+          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
