Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,7 +1,19 @@
-name: Build and Release YTLitePlusEXTRA IPA
+name: (Pre-Release) Build YTLitePlusEXTRA IPA
 on:
   workflow_dispatch:
-    inputs:      
+    inputs:
+      ipa_url:
+        description: "URL to the decrypted IPA file"
+        default: ""
+        required: true
+        type: string
+
+      deb_url:
+        description: "URL to your YTLite .deb file"
+        default: ""
+        required: true
+        type: string
+
       display_name:
         description: "App Name (Optional)"
         default: "YouTube"
@@ -15,13 +27,7 @@ on:
         type: string
 
       upload_artifact:
-        description: "Upload IPA as an Artifact (Public)"
-        default: true
-        required: false
-        type: boolean
-        
-      catbox_upload:
-        description: "Upload IPA to Catbox.moe (URL)"
+        description: "Upload IPA as an artifact (Public)"
         default: true
         required: false
         type: boolean
@@ -38,48 +44,48 @@ concurrency:
 
 jobs:
   build:
-    name: Build and Release YTLitePlusEXTRA IPA
+    name: Build YTLitePlusEXTRA IPA
     runs-on: macos-latest
     permissions:
       contents: write
 
     steps:
+      - name: Check Inputs
+        if: ${{ !inputs.upload_artifact && !inputs.draft_release }}
+        run: |
+          echo "No IPA output way selected. Please choose at least one."
+          exit 1
+
       - name: Hide Sensitive Inputs
         uses: levibostian/action-hide-sensitive-inputs@v1
         with:
-          exclude_inputs: bundle_id,display_name,tweak_version,draft_release,catbox_upload,upload_artifact
+          exclude_inputs: bundle_id,display_name,tweak_version,draft_release,upload_artifact
           
       - name: Download and Validate IPA
         run: |
-          wget https://archive.org/download/com.google.ios.youtube-20.21.6-Decrypted/com.google.ios.youtube-20.21.6-Decrypted.ipa --no-verbose -O ${{ github.workspace }}/youtube.ipa
+          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa
 
-          file_type=$(file --mime-type -b ${{ github.workspace }}/youtube.ipa)
+          ipa_type=$(file --mime-type -b ${{ github.workspace }}/youtube.ipa)
 
-          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
-            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
+          if [[ "$ipa_type" != "application/x-ios-app" && "$ipa_type" != "application/zip" ]]; then
+            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $ipa_type."
             exit 1
           fi
-
-      - name: Get Youtube Version 
+ 
+      - name: Get YouTube Version 
         run: |
-          mkdir -p ${{ github.workspace }}/ytversion
-          cp -r ${{ github.workspace }}/youtube.ipa ${{ github.workspace }}/ytversion/youtube.ipa
-          unzip -q ${{ github.workspace }}/ytversion/youtube.ipa -d ${{ github.workspace }}/ytversion/ytextracted
-          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ${{ github.workspace }}/ytversion/ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
+          unzip -q ${{ github.workspace }}/youtube.ipa -d ${{ github.workspace }}/ytextracted
+          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ${{ github.workspace }}/ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
           echo -e 'Done!'
 
       - name: Install Dependencies
-        run: brew install make ldid dpkg
+        run: brew install make ldid swiftlint
 
       - name: Set PATH Environment Variable
         run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
 
       - name: Clone Theos
-        uses: actions/checkout@v5
-        with:
-          repository: theos/theos
-          path: ${{ github.workspace }}/theos
-          submodules: recursive
+        run: git clone --quiet --recurse-submodules https://github.com/theos/theos.git
         
       - name: Download iOS SDK
         run: |
@@ -97,9 +103,33 @@ jobs:
           wget --no-verbose https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac -O /usr/local/bin/tbd
           chmod +x /usr/local/bin/tbd 
 
-      - name: Download YTLite
+      - name: Download and Validate your YTLite .deb 
         run: |
-          wget https://files.catbox.moe/v50glr.deb --no-verbose -O ${{ github.workspace }}/ytlite.deb
+          wget "${{ inputs.deb_url }}" --no-verbose -O ${{ github.workspace }}/ytlite.deb
+
+          deb_type=$(file --mime-type -b ${{ github.workspace }}/ytlite.deb)
+
+          if [[ "$deb_type" != "application/vnd.debian.binary-package" ]]; then
+            echo "::error::Validation failed: The downloaded file is not a valid deb. Detected type: $deb_type."
+            exit 1
+          fi
+
+      - name: Get YTLite Version
+        run: |
+          cd ${{ github.workspace }}
+          ar x ytlite.deb control.tar.gz >/dev/null 2>&1
+          tar -xzf control.tar.gz ./control
+          VERSION=$(grep '^Version:' control | cut -d ' ' -f2)
+          echo "YTLITE_VERSION=$VERSION" >> $GITHUB_ENV
+          echo -e 'Done!'
+
+      - name: Clone Open in YouTube (Safari Extension)
+        run: |
+          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension.git
+          cd OpenYouTubeSafariExtension
+          git sparse-checkout set --no-cone OpenYouTubeSafariExtension.appex
+          git checkout
+          mv *.appex ${{ github.workspace }}
 
       - name: Clone YouTubeHeader
         run: |
@@ -116,36 +146,246 @@ jobs:
         env:
           THEOS: ${{ github.workspace }}/theos
 
+      - name: Clone YouPiP
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git
+    
       - name: Clone YTUHD
-        run: |
-           git clone --quiet https://github.com/PoomSmart/YTUHD.git
+        uses: actions/checkout@v5
+        with:
+          repository: PoomSmart/YTUHD
+          ref: 0f59b38817d554ab692a0053456319847a6ab1a1
+          path: ${{ github.workspace }}/YTUHD
+          submodules: recursive
 
-      - name: Download libundirect
-        run: wget --no-verbose https://github.com/opa334/opa334.github.io/raw/refs/heads/master/debs/com.opa334.libundirect_1.1.6_iphoneos-arm64.deb -O ${{ github.workspace }}/libundirect.deb
-
-      - name: Clone ElleKit
+      - name: Clone Return-YouTube-Dislikes
         run: |
-           git clone --quiet https://github.com/tealbathingsuit/ellekit.git
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git
 
-      - name: Build ElleKit
+      - name: Clone YouGroupSettings
         run: |
-          cd ${{ github.workspace }}/ellekit
-          make deb
-          mv packages/*arm64.deb ${{ github.workspace }}/ellekit.deb
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git
+           
+      - name: Clone YTVideoOverlay
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git
+          
+      - name: Clone YTABConfig
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
+                  
+      - name: Clone YouQuality
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git
+
+      - name: Clone YouSpeed
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/YouSpeed.git
+
+      - name: Clone DontEatMyContent
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/therealFoxster/DontEatMyContent.git
+
+      - name: Clone IAmYouTube
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/IAmYouTube.git
+
+      - name: Clone YouMute
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/YouMute.git
+
+      - name: Clone YTABGoodies
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/PoomSmart/YTABGoodies.git
+
+      - name: Clone YouTimeStamp
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/Tonwalter888/YouTimeStamp.git
+    
+      - name: Clone YouLoop
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/Tonwalter888/YouLoop.git
+
+      - name: Clone Alderis
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/hbang/Alderis.git
+
+      - name: Clone YouSlider
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/PoomSmart/YouSlider.git
+
+      - name: Clone YouChooseQuality
+        run: |
+           cd ${{ github.workspace }}
+           git clone --quiet --depth=1 https://github.com/PoomSmart/YouChooseQuality.git
+
+      - name: Clone YTSilentVote
+        run: |
+          cd ${{ github.workspace }}
+          git clone --quiet --depth=1 https://github.com/PoomSmart/YTSilentVote.git
+      
+      - name: Build YouPiP
+        run: |
+          cd ${{ github.workspace }}/YouPiP
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youpip.deb
         env:
-          THEOS: ${{ github.workspace }}/theos
+          THEOS: ${{ github.workspace }}/theos    
 
       - name: Build YTUHD
         run: |
           cd ${{ github.workspace }}/YTUHD
-          make clean package FINALPACKAGE=1 SIDELOAD=1
+          make clean package DEBUG=0 FINALPACKAGE=1
           mv packages/*.deb ${{ github.workspace }}/ytuhd.deb
         env:
           THEOS: ${{ github.workspace }}/theos
+
+      - name: Build Return-YouTube-Dislikes
+        run: |
+          cd ${{ github.workspace }}/Return-YouTube-Dislikes
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ryd.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouGroupSettings
+        run: |
+          cd ${{ github.workspace }}/YouGroupSettings
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ygs.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YTVideoOverlay
+        run: |
+          cd ${{ github.workspace }}/YTVideoOverlay
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ytvo.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YTABConfig
+        run: |
+          cd ${{ github.workspace }}/YTABConfig
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ytabconfig.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouQuality
+        run: |
+          cd ${{ github.workspace }}/YouQuality
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youquality.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouSpeed
+        run: |
+          cd ${{ github.workspace }}/YouSpeed
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youspeed.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build DontEatMyContent
+        run: |
+          cd ${{ github.workspace }}/DontEatMyContent
+          make clean package DEBUG=0 FINALPACKAGE=1 
+          mv packages/*.deb ${{ github.workspace }}/demc.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build IAmYouTube
+        run: |
+          cd ${{ github.workspace }}/IAmYouTube
+          make clean package DEBUG=0 FINALPACKAGE=1 
+          mv packages/*.deb ${{ github.workspace }}/imyt.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouMute
+        run: |
+          cd ${{ github.workspace }}/YouMute
+          make clean package DEBUG=0 FINALPACKAGE=1 
+          mv packages/*.deb ${{ github.workspace }}/ym.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos 
+
+      - name: Build YTABGoodies
+        run: |
+          cd ${{ github.workspace }}/YTABGoodies
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ytgoodab.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouTimeStamp
+        run: |
+          cd ${{ github.workspace }}/YouTimeStamp
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youts.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouLoop
+        run: |
+          cd ${{ github.workspace }}/YouLoop
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youloop.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouSlider
+        run: |
+          cd ${{ github.workspace }}/YouSlider
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youslider.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build Alderis
+        run: |
+          cd ${{ github.workspace }}/Alderis
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/alderis.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YouChooseQuality
+        run: |
+          cd ${{ github.workspace }}/YouChooseQuality
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/youchoose.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos
+
+      - name: Build YTSilentVote
+        run: |
+          cd ${{ github.workspace }}/YTSilentVote
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ytnovote.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos  
   
       - name: Inject Tweaks Into IPA
         run: |
-          tweaks="ytlite.deb"
+          tweaks="ytlite.deb OpenYouTubeSafariExtension.appex"
 
           for f in *.deb; do
             if [ -f "$f" ]; then
@@ -153,57 +393,38 @@ jobs:
             fi
           done
           
-          cyan -i youtube.ipa -o almostfinish.ipa -uwf $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}
-          mkdir -p removecydia
-          unzip -q almostfinish.ipa -d removecydia
-          find removecydia/Payload -name "CydiaSubstrate.framework" -exec rm -rf {} +
-          find removecydia/Payload -name "libsubstrate.dylib" -exec rm -f {} +
-          PLIST=removecydia/Payload/YouTube.app/Info.plist
-          /usr/libexec/PlistBuddy -c "Delete :DynamicLibraries:libsubstrate.dylib" "$PLIST" || true
-          cd removecydia
-          zip -qr ../YTLitePlusEXTRA_${{ env.YT_VERSION }}_v5.2b4.ipa Payload
-
-      - name: Upload IPA to Catbox
-        if: ${{ inputs.catbox_upload }}
-        run: |
-          RESPONSE=$(curl -F "reqtype=fileupload" -F "fileToUpload=@${{ github.workspace }}/YTLitePlusEXTRA_${{ env.YT_VERSION }}_v5.2b4.ipa" https://catbox.moe/user/api.php)
-          CATBOX_URL=$(echo $RESPONSE | grep -o -E 'https://files.catbox.moe/[^"]*')
-          echo "Uploaded artifact to $CATBOX_URL"
-          CATBOX_FILE=$(echo $CATBOX_URL | sed 's|https://files.catbox.moe/||')
-          echo "CATBOX_FILE=$CATBOX_FILE" >> $GITHUB_ENV
-          echo "CATBOX_URL=$CATBOX_URL" >> $GITHUB_ENV
+          cyan -i youtube.ipa -o YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}
 
       - name: Upload IPA as an Artifact
         if: ${{ inputs.upload_artifact }}
         uses: actions/upload-artifact@v4.6.2
         with:
-          name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v5.2b4
-          path: ${{ github.workspace }}/YTLitePlusEXTRA_${{ env.YT_VERSION }}_v5.2b4.ipa
+          name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }}
+          path: ${{ github.workspace }}/YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }}.ipa
 
       - name: Create a Draft Release
         if: ${{ inputs.draft_release }}
         uses: softprops/action-gh-release@v2.3.3
         with:
-          tag_name: ytliteplusextra-ipa${{ github.run_number }}
-          name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v5.2b4 (${{ github.run_number }}) 
-          files: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v5.2b4.ipa
+          tag_name: ytliteplusextra-pre-release-ipa${{ github.run_number }}
+          name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }} (${{ github.run_number }}) 
+          files: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }}.ipa
           draft: true
 
-      - name: Output an Artifact Upload
+      - name: Job Summary - Build Complete
+        run: |
+          echo -e '### 🛠️ Build YTLitePlusEXTRA IPA Complete!' >> $GITHUB_STEP_SUMMARY
+
+      - name: Job Summary - Output the Artifact Upload
         if: ${{ inputs.upload_artifact }}
         run: |
-          echo -e '### 📦 Artifact Upload\n\nThe artifact was uploaded successfully! Refresh and [scroll down](#artifacts) to view the artifact. Note that you must be signed in to GitHub to download it.' >> $GITHUB_STEP_SUMMARY
+          echo -e '### 📦 Artifact Upload\n\nUpload IPA as an artifact successfully! [Scroll down](#artifacts) to view the artifact. Note that you must be signed in to GitHub to download it.' >> $GITHUB_STEP_SUMMARY
 
-      - name: Output IPA URL Link (Catbox Upload)
-        if: ${{ inputs.catbox_upload}}
-        run: |
-          echo -e '### 🐱 Catbox Upload\n\nThe Catbox upload was successful! Here is a permanent shareable link: '$CATBOX_URL >> $GITHUB_STEP_SUMMARY
-
-      - name: Output a Draft Release Link
+      - name: Job Summary - Output a Draft Release Link
         if: ${{ inputs.draft_release }}
         run: |
-          echo -e '### 🚀 Draft Release\n\nThe release draft has been created successfully! You can view your releases here: https://github.com/${{ github.repository }}/releases' >> $GITHUB_STEP_SUMMARY
+          echo -e '### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases' >> $GITHUB_STEP_SUMMARY
      
-      - name: Cleanup
+      - name: Job Summary - Cleanup
         run: |
-          echo -e '### 🧹 Cleanup\n\nYou can remove previous GitHub Action runs here: https://github.com/${{ github.repository }}/actions/workflows/delete-workflow-runs.yml' >> $GITHUB_STEP_SUMMARY
+          echo -e '### 🧹 Cleanup\n\nYou can remove previous GitHub Action runs here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflows-run.yml' >> $GITHUB_STEP_SUMMARY
